/** Autogenerated source code, do not edit!
 */
 
//C++ includes
#include <vector>
#include <cmath>
 
//Include the text of the SBML in here.
//Use "xxd -i" to get the text as a C symbol.
extern "C" unsigned char __original_sbml[] = "";
 
//Constants and other functions defined by the SBML standard.
 
//Get the correct floating point type from the code at runtime.
typedef double reaction_rate_t;
typedef reaction_rate_t Real;
 
//Prototype all the functions
static inline Real Constant_flux__irreversible(Real v);
static inline Real v_pump(Real S_V, Real k_pump, Real ATP, Real NA, Real Km_pump);
static inline Real function_1(Real S_V, Real gNA, Real F, Real RT_F, Real Na_e, Real Na, Real Vm);
static inline Real v_GLC_m(Real Tmax, Real GLC_c, Real Kt_GLC, Real GLC_i);
static inline Real function_2(Real ATP, Real GLC_i, Real Kg, Real KI_ATP, Real nH, Real kHK_PFK);
static inline Real v_PGK(Real kPGK, Real GAP, Real ADP, Real NAD, Real NADH);
static inline Real v_LAC_m(Real Tmax, Real LAC_i, Real Kt_LAC, Real LAC_c);
static inline Real v_O2_m(Real PS_V, Real KO2, Real HbOP, Real O2_c, Real nh, Real O2_i);
static inline Real v_O2_c(Real F_in, Real V_cap, Real O2_a, Real O2_c);
static inline Real v_GLC_c(Real F_in, Real V_cap, Real GLC_a, Real GLC_c);
static inline Real v_LAC_c(Real F_in, Real V_cap, Real LAC_a, Real LAC_c);
static inline Real v_dHb_in(Real F_in, Real O2_a, Real O2_c);
static inline Real v_dHb_out(Real F_out, Real dHb, Real V_v);
 
//Define all the constants and initial states
static constexpr const Real parameter_31 = 10;
static constexpr const Real parameter_1 = 90000;
static constexpr const Real parameter_2 = 0.0039;
static constexpr const Real parameter_3 = 96500;
static constexpr const Real parameter_4 = 26.73;
static constexpr const Real parameter_5 = -70;
static constexpr const Real parameter_6 = 150;
static constexpr const Real parameter_8 = 2.9e-007;
static constexpr const Real parameter_9 = 0.5;
static constexpr const Real parameter_11 = 0.92;
static constexpr const Real parameter_12 = 2.212;
static constexpr const Real parameter_14 = 0.0476;
static constexpr const Real parameter_15 = 9;
static constexpr const Real parameter_16 = 0.12;
static constexpr const Real parameter_17 = 1;
static constexpr const Real parameter_18 = 4;
static constexpr const Real parameter_19 = 0.05;
static constexpr const Real parameter_20 = 42.6;
static constexpr const Real parameter_21 = 0.212;
static constexpr const Real parameter_23 = 86.7;
static constexpr const Real parameter_24 = 2000;
static constexpr const Real parameter_25 = 44.8;
static constexpr const Real parameter_26 = 0.00628;
static constexpr const Real parameter_27 = 0.5;
static constexpr const Real parameter_28 = 0.149;
static constexpr const Real parameter_29 = 3666;
static constexpr const Real parameter_30 = 20;
static constexpr const Real parameter_32 = 1.6;
static constexpr const Real parameter_33 = 0.0361;
static constexpr const Real parameter_34 = 8.6;
static constexpr const Real parameter_35 = 2.73;
static constexpr const Real parameter_36 = 0.012;
static constexpr const Real parameter_38 = 0.0055;
static constexpr const Real parameter_47 = 0.0192;
static constexpr const Real V_max_Mito = 0.05233;
static constexpr const Real Km_Mito = 0.05;
static constexpr const Real KI_Mito = 183.3;
static constexpr const Real n_Mito = 0.1;
static constexpr const Real K_O2_Mito = 0.001;
static constexpr const Real alpha_F_in = 0.5;
static constexpr const Real t_on = 5;
static constexpr const Real t_end = 360;
static constexpr const Real ATPases_v = 0.149;
static constexpr const Real _init_is_maximum = 0;
static constexpr const Real _init_is_rising = 1;
static constexpr const Real _init_is_falling = 0;
static constexpr const Real _init_parameter_7 = 2.2;
static constexpr const Real _init_v_stim_constant = 0.23;
static constexpr const Real _init_compartment_4 = 0.0237;
static constexpr const Real compartment_1 = 1;
static constexpr const Real compartment_2 = 1;
static constexpr const Real compartment_3 = 1;
static constexpr const Real ModelValue_52 = t_on;
static constexpr const Real ModelValue_53 = t_end;
static constexpr const Real ModelValue_35 = parameter_36;
static constexpr const Real ModelValue_50 = alpha_F_in;
static constexpr const Real Compartment_7 = _init_compartment_4;
static constexpr const Real _init_species_1 = 15/compartment_1;
static constexpr const Real _init_species_4 = 1.2/compartment_1;
static constexpr const Real _init_species_5 = 0.0057/compartment_1;
static constexpr const Real _init_species_7 = 0.026/compartment_1;
static constexpr const Real _init_species_8 = 0.16/compartment_1;
static constexpr const Real _init_species_9 = 0.02/compartment_1;
static constexpr const Real _init_species_10 = 1/compartment_1;
static constexpr const Real _init_species_11 = 5/compartment_1;
static constexpr const Real _init_species_13 = 0.0262/compartment_1;
static constexpr const Real _init_species_14 = 8.34/compartment_2;
static constexpr const Real _init_species_15 = 4.8/compartment_2;
static constexpr const Real _init_species_16 = 0.313/compartment_2;
static constexpr const Real _init_species_17 = 4.56/compartment_3;
static constexpr const Real _init_species_18 = 0.35/compartment_3;
static constexpr const Real _init_species_19 = 7.01/compartment_3;
static constexpr const Real _init_dHb = 0.0630000000000001/compartment_3;
static constexpr const Real maximum = ModelValue_35*ModelValue_50;
static constexpr const Real ModelValue_51 = maximum;
 
extern "C" Real __init_is_maximum = _init_is_maximum;
extern "C" Real __init_is_rising = _init_is_rising;
extern "C" Real __init_is_falling = _init_is_falling;
extern "C" Real __init_parameter_7 = _init_parameter_7;
extern "C" Real __init_v_stim_constant = _init_v_stim_constant;
extern "C" Real __init_compartment_4 = _init_compartment_4;
extern "C" Real __init_species_1 = _init_species_1;
extern "C" Real __init_species_4 = _init_species_4;
extern "C" Real __init_species_5 = _init_species_5;
extern "C" Real __init_species_7 = _init_species_7;
extern "C" Real __init_species_8 = _init_species_8;
extern "C" Real __init_species_9 = _init_species_9;
extern "C" Real __init_species_10 = _init_species_10;
extern "C" Real __init_species_11 = _init_species_11;
extern "C" Real __init_species_13 = _init_species_13;
extern "C" Real __init_species_14 = _init_species_14;
extern "C" Real __init_species_15 = _init_species_15;
extern "C" Real __init_species_16 = _init_species_16;
extern "C" Real __init_species_17 = _init_species_17;
extern "C" Real __init_species_18 = _init_species_18;
extern "C" Real __init_species_19 = _init_species_19;
extern "C" Real __init_dHb = _init_dHb;
  
//Define the functions
static Real Constant_flux__irreversible(Real v) {
  return v;
}
 
static inline Real v_pump(Real S_V, Real k_pump, Real ATP, Real NA, Real Km_pump) {
  return (S_V*k_pump*ATP*NA)/(1 + ATP/Km_pump);
}
 
static inline Real function_1(Real S_V, Real gNA, Real F, Real RT_F, Real Na_e, Real Na, Real Vm) {
  return S_V*(gNA/F)*(RT_F*log(Na_e/Na) - Vm);
}
 
static inline Real v_GLC_m(Real Tmax, Real GLC_c, Real Kt_GLC, Real GLC_i) {
  return Tmax*(GLC_c/(GLC_c + Kt_GLC) - GLC_i/(GLC_i + Kt_GLC));
}
 
static inline Real function_2(Real ATP, Real GLC_i, Real Kg, Real KI_ATP, Real nH, Real kHK_PFK) {
  return (kHK_PFK*ATP*(GLC_i/(GLC_i + Kg)))/(1 + pow(ATP/KI_ATP,nH));
}
 
static inline Real v_PGK(Real kPGK, Real GAP, Real ADP, Real NAD, Real NADH) {
  return kPGK*GAP*ADP*(NAD/NADH);
}
 
static inline Real v_LAC_m(Real Tmax, Real LAC_i, Real Kt_LAC, Real LAC_c) {
  return Tmax*(LAC_i/(LAC_i + Kt_LAC) - LAC_c/(LAC_c + Kt_LAC));
}
 
static inline Real v_O2_m(Real PS_V, Real KO2, Real HbOP, Real O2_c, Real nh, Real O2_i) {
  return PS_V*(KO2*pow((HbOP/O2_c - 1),(-1/nh)) - O2_i);
}
 
static inline Real v_O2_c(Real F_in, Real V_cap, Real O2_a, Real O2_c) {
  return (2*F_in)/V_cap*(O2_a - O2_c);
}
 
static inline Real v_GLC_c(Real F_in, Real V_cap, Real GLC_a, Real GLC_c) {
  return (2*F_in)/V_cap*(GLC_a - GLC_c);
}
 
static inline Real v_LAC_c(Real F_in, Real V_cap, Real LAC_a, Real LAC_c) {
  return (2*F_in)/V_cap*(LAC_a - LAC_c);
}
 
static inline Real v_dHb_in(Real F_in, Real O2_a, Real O2_c) {
  return F_in*2*(O2_a - O2_c);
}
 
static inline Real v_dHb_out(Real F_out, Real dHb, Real V_v) {
   return (F_out*dHb)/V_v;
}
 
//Define the rates
extern "C" Real __rate_reaction_4(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_4 = __input[__ii++];
   Real parameter_7 = __input[__ii++];
   Real species_2 = parameter_7*compartment_1;
   Real reaction_4 = compartment_1*function_2(species_2/compartment_1, species_4/compartment_1, parameter_19, parameter_17, parameter_18, parameter_16);
   return reaction_4;
}
 
extern "C" Real __rate_reaction_5(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_7 = __input[__ii++];
   Real species_5 = __input[__ii++];
   Real parameter_7 = __input[__ii++];
   Real parameter_22 = parameter_21 - species_7/compartment_1;
   Real species_6 = parameter_22*compartment_1;
   Real parameter_10 = parameter_7/2*(-parameter_11 + pow(pow(parameter_11,2) + 4*parameter_11*(parameter_12/parameter_7 - 1),0.5));
   Real species_3 = parameter_10*compartment_1;
   Real reaction_5 = compartment_1*v_PGK(parameter_20, species_5/compartment_1, species_3/compartment_1, species_6/compartment_1, species_7/compartment_1);
   return reaction_5;
}
 
extern "C" Real __rate_reaction_6(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_9 = __input[__ii++];
   Real parameter_7 = __input[__ii++];
   Real parameter_10 = parameter_7/2*(-parameter_11 + pow(pow(parameter_11,2) + 4*parameter_11*(parameter_12/parameter_7 - 1),0.5));
   Real species_3 = parameter_10*compartment_1;
   Real reaction_6 = parameter_23*species_3*(species_9/compartment_1);
   return reaction_6;
}
 
extern "C" Real __rate_reaction_2(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_1 = __input[__ii++];
   Real parameter_7 = __input[__ii++];
   Real species_2 = parameter_7*compartment_1;
   Real reaction_2 = compartment_1*v_pump(parameter_1, parameter_8, species_2/compartment_1, species_1/compartment_1, parameter_9);
   return reaction_2;
}
 
extern "C" Real __rate_mitochondrial_respiration(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_8 = __input[__ii++];
   Real species_13 = __input[__ii++];
   Real parameter_7 = __input[__ii++];
   Real parameter_10 = parameter_7/2*(-parameter_11 + pow(pow(parameter_11,2) + 4*parameter_11*(parameter_12/parameter_7 - 1),0.5));
   Real v_Mito_H3 = V_max_Mito*(species_8/compartment_1/(Km_Mito + species_8/compartment_1))*(1/(1 + pow(parameter_7/(parameter_10*KI_Mito),n_Mito)))*(species_13/compartment_1/(K_O2_Mito + species_13/compartment_1));
   Real mitochondrial_respiration = compartment_1*Constant_flux__irreversible(v_Mito_H3);
   return mitochondrial_respiration;
}
 
extern "C" Real __rate_reaction_9(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_11 = __input[__ii++];
   Real species_12 = __input[__ii++];
   Real parameter_7 = __input[__ii++];
   Real parameter_10 = parameter_7/2*(-parameter_11 + pow(pow(parameter_11,2) + 4*parameter_11*(parameter_12/parameter_7 - 1),0.5));
   Real species_2 = parameter_7*compartment_1;
   Real species_3 = parameter_10*compartment_1;
   Real reaction_9 = compartment_1*(parameter_29*(species_11/compartment_1)*(species_3/compartment_1) - parameter_30*(species_12/compartment_1)*(species_2/compartment_1));
   return reaction_9;
}
 
extern "C" Real __rate_ATPases(const std::vector<Real>& __input) {
   int __ii=0;
   return compartment_1*Constant_flux__irreversible(ATPases_v);
}
 
extern "C" Real __rate_reaction_1(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_1 = __input[__ii++];
   Real reaction_1 = compartment_1*function_1(parameter_1, parameter_2, parameter_3, parameter_4, parameter_6, species_1/compartment_1, parameter_5);
   return reaction_1;
}
 
extern "C" Real __rate_reaction_3(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_17 = __input[__ii++];
   Real species_4 = __input[__ii++];
   Real reaction_3 = v_GLC_m(parameter_14, species_17/compartment_3, parameter_15, species_4/compartment_1);
   return reaction_3;
}
 
extern "C" Real __rate_reaction_7(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_8 = __input[__ii++];
   Real species_7 = __input[__ii++];
   Real species_10 = __input[__ii++];
   Real parameter_22 = parameter_21 - species_7/compartment_1;
   Real species_6 = parameter_22*compartment_1;
   Real reaction_7 = compartment_1*(parameter_24*(species_8/compartment_1)*(species_7/compartment_1) - parameter_25*(species_10/compartment_1)*(species_6/compartment_1));
   return reaction_7;
}
 
extern "C" Real __rate_reaction_8(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_10 = __input[__ii++];
   Real species_18 = __input[__ii++];
   Real reaction_8 = v_LAC_m(parameter_26, species_10/compartment_1, parameter_27, species_18/compartment_3);
   return reaction_8;
}
 
extern "C" Real __rate_reaction_10(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_19 = __input[__ii++];
   Real species_13 = __input[__ii++];
   Real reaction_10 = v_O2_m(parameter_32, parameter_33, parameter_34, species_19/compartment_3, parameter_35, species_13/compartment_1);
   return reaction_10;
}
 
extern "C" Real __rate_reaction_11(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_14 = __input[__ii++];
   Real species_19 = __input[__ii++];
   Real time = __input[__ii++];
   Real is_rising = __input[__ii++];
   Real is_maximum = __input[__ii++];
   Real is_falling = __input[__ii++];
   Real maximum = ModelValue_35*ModelValue_50;
   Real slope_up = ModelValue_51/ModelValue_52*time;
   Real slope_down = (maximum*((t_on + t_end) - time))/t_on;
   Real parameter_37 = parameter_36 + is_rising*slope_up + is_maximum*maximum + is_falling*slope_down;
   Real reaction_11 = v_O2_c(parameter_37, parameter_38, species_14/compartment_2, species_19/compartment_3);
   return reaction_11;
}
 
extern "C" Real __rate_reaction_12(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_15 = __input[__ii++];
   Real species_17 = __input[__ii++];
   Real time = __input[__ii++];
   Real is_rising = __input[__ii++];
   Real is_maximum = __input[__ii++];
   Real is_falling = __input[__ii++];
   Real maximum = ModelValue_35*ModelValue_50;
   Real slope_up = ModelValue_51/ModelValue_52*time;
   Real slope_down = (maximum*((t_on + t_end) - time))/t_on;
   Real parameter_37 = parameter_36 + is_rising*slope_up + is_maximum*maximum + is_falling*slope_down;
   Real reaction_12 = v_GLC_c(parameter_37, parameter_38, species_15/compartment_2, species_17/compartment_3);
   return reaction_12;
}
 
extern "C" Real __rate_reaction_13(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_16 = __input[__ii++];
   Real species_18 = __input[__ii++];
   Real time = __input[__ii++];
   Real is_rising = __input[__ii++];
   Real is_maximum = __input[__ii++];
   Real is_falling = __input[__ii++];
   Real maximum = ModelValue_35*ModelValue_50;
   Real slope_up = ModelValue_51/ModelValue_52*time;
   Real slope_down = (maximum*((t_on + t_end) - time))/t_on;
   Real parameter_37 = parameter_36 + is_rising*slope_up + is_maximum*maximum + is_falling*slope_down;
   Real reaction_13 = v_LAC_c(parameter_37, parameter_38, species_16/compartment_2, species_18/compartment_3);
   return reaction_13;
}
 
extern "C" Real __rate_Na__inflow_after_stimulation(const std::vector<Real>& __input) {
   int __ii=0;
   Real v_stim_constant = __input[__ii++];
   Real Na__inflow_after_stimulation = compartment_1*Constant_flux__irreversible(v_stim_constant);
   return Na__inflow_after_stimulation;
}
 
extern "C" Real __rate__inflow_of_dHb(const std::vector<Real>& __input) {
   int __ii=0;
   Real species_14 = __input[__ii++];
   Real species_19 = __input[__ii++];
   Real time = __input[__ii++];
   Real is_rising = __input[__ii++];
   Real is_maximum = __input[__ii++];
   Real is_falling = __input[__ii++];
   Real maximum = ModelValue_35*ModelValue_50;
   Real slope_up = ModelValue_51/ModelValue_52*time;
   Real slope_down = (maximum*((t_on + t_end) - time))/t_on;
   Real parameter_37 = parameter_36 + is_rising*slope_up + is_maximum*maximum + is_falling*slope_down;  
   Real inflow_of_dHb = compartment_3*v_dHb_in(parameter_37, species_14/compartment_2, species_19/compartment_3);
   return inflow_of_dHb;
}
 
extern "C" Real __rate_outflow_of_dHb(const std::vector<Real>& __input) {
   int __ii=0;
   Real dHb = __input[__ii++];
   Real compartment_4 = __input[__ii++];
   Real time = __input[__ii++];
   Real is_rising = __input[__ii++];
   Real is_maximum = __input[__ii++];
   Real is_falling = __input[__ii++];
   Real maximum = ModelValue_35*ModelValue_50;
   Real slope_up = ModelValue_51/ModelValue_52*time;
   Real slope_down = (maximum*((t_on + t_end) - time))/t_on;
   Real parameter_37 = parameter_36 + is_rising*slope_up + is_maximum*maximum + is_falling*slope_down;  
   Real F_out = (parameter_36*(pow(compartment_4/Compartment_7,2) + pow(compartment_4/Compartment_7,-0.5)*35*(1/Compartment_7)*parameter_37))/(1 + parameter_36*pow(compartment_4/Compartment_7,-0.5)*35*(1/Compartment_7));
   Real outflow_of_dHb = compartment_3*v_dHb_out(F_out, dHb/compartment_3, compartment_4);
   return outflow_of_dHb;
}
 
 
//Define differential rates
extern "C" Real __rate_compartment_4(const std::vector<Real>& __input) {
   int __ii=0;
   Real compartment_4 = __input[__ii++];
   Real time = __input[__ii++];
   Real is_rising = __input[__ii++];
   Real is_maximum = __input[__ii++];
   Real is_falling = __input[__ii++];
   Real maximum = ModelValue_35*ModelValue_50;
   Real slope_up = ModelValue_51/ModelValue_52*time;
   Real slope_down = (maximum*((t_on + t_end) - time))/t_on;
   Real parameter_37 = parameter_36 + is_rising*slope_up + is_maximum*maximum + is_falling*slope_down;  
   Real F_out = (parameter_36*(pow(compartment_4/Compartment_7,2) + pow(compartment_4/Compartment_7,-0.5)*35*(1/Compartment_7)*parameter_37))/(1 + parameter_36*pow(compartment_4/Compartment_7,-0.5)*35*(1/Compartment_7));
 
   return parameter_37 - F_out;
}
 
extern "C" Real __rate_parameter_7(const std::vector<Real>& __input) {
   int __ii=0;
   Real parameter_7 = __input[__ii++];
   Real species_4 = __input[__ii++];
   Real species_5 = __input[__ii++];
   Real species_7 = __input[__ii++];
   Real species_9 = __input[__ii++];
   Real species_1 = __input[__ii++];
   Real species_8 = __input[__ii++];
   Real species_13 = __input[__ii++];
   Real species_11 = __input[__ii++];
   Real species_2 = parameter_7*compartment_1;
   Real parameter_10 = parameter_7/2*(-parameter_11 + pow(pow(parameter_11,2) + 4*parameter_11*(parameter_12/parameter_7 - 1),0.5));
   Real species_3 = parameter_10*compartment_1;
   Real parameter_22 = parameter_21 - species_7/compartment_1;
   Real species_6 = parameter_22*compartment_1;
   Real v_Mito_H3 = V_max_Mito*(species_8/compartment_1/(Km_Mito + species_8/compartment_1))*(1/(1 + pow(parameter_7/(parameter_10*KI_Mito),n_Mito)))*(species_13/compartment_1/(K_O2_Mito + species_13/compartment_1));
   Real species_12 = (parameter_31 - species_11/compartment_1)*compartment_1;
   Real dAMP_dATP = (-1 + parameter_11/2) - 1/2*pow(pow(parameter_11,2) + 4*parameter_11*(parameter_12/parameter_7 - 1),1/2) + (parameter_11*parameter_12)/(parameter_7*pow(pow(parameter_11,2) + 4*parameter_11*(parameter_12/parameter_7 - 1),1/2));
   Real reaction_4 = compartment_1*function_2(species_2/compartment_1, species_4/compartment_1, parameter_19, parameter_17, parameter_18, parameter_16);
   Real reaction_5 = compartment_1*v_PGK(parameter_20, species_5/compartment_1, species_3/compartment_1, species_6/compartment_1, species_7/compartment_1);
   Real reaction_6 = parameter_23*species_3*(species_9/compartment_1);
   Real reaction_2 = compartment_1*v_pump(parameter_1, parameter_8, species_2/compartment_1, species_1/compartment_1, parameter_9);
   Real mitochondrial_respiration = compartment_1*Constant_flux__irreversible(v_Mito_H3);
   Real reaction_9 = compartment_1*(parameter_29*(species_11/compartment_1)*(species_3/compartment_1) - parameter_30*(species_12/compartment_1)*(species_2/compartment_1));
   Real ATPases = compartment_1*Constant_flux__irreversible(ATPases_v);
    
   return (((-2*reaction_4 + reaction_5 + reaction_6) - reaction_2 + 15*mitochondrial_respiration + reaction_9) - ATPases)/(1 - dAMP_dATP);
}


